---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_enablerepo: "remi,remi-php72"
    php_default_version_debian: "7.2"
    php_pear_channels:
      - pear.phing.info
    php_pear_libraries:
      - phing/phingdocs

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.php
    - role: geerlingguy.php-pear
