---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_enablerepo: "remi,remi-php70"

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.php
    - role: geerlingguy.php-pear
